
### Test de usuarios

### get de usuarios 
GET http://localhost:8080/users/100546


### post de usuarios
POST http://localhost:8080/users
Content-Type: application/json

{
  "name":"Crisali", "email":"allisonhincapie259@gmail.com", "username":"Crisali21", "password":"1234567890", "image":"https://firebasestorage.googleapis.com/v0/b/star-neutron.appspot.com/o/background-1.png?alt=media&token=53458d0f-f4bd-452a-be2a-dad4a74e3ad7"
}

### put de usuarios 
PUT http://localhost:8080/users/8475dd28-ae03-40e1-b6e5-fe85f0f0b650
Content-Type: application/json

{
  "name":"Juan Emilio Molano", "email":"juansito@gmail.com", "username":"juanMasterKiller", "password":"1234567890"
}

### delete de usuarios
DELETE  http://localhost:8080/users/8475dd28-ae03-40e1-b6e5-fe85f0f0b650


### Test de asignaturas

### obtener una asignatura por su id
GET http://localhost:8080/subjects/777


###obtener las asignaturas de un usuario
GET http://localhost:8080/subjects/user/100546

### crear una asignatura
POST http://localhost:8080/subjects
Content-Type: application/json

{
  "name":"Matematicas", "color":"#FFFFFF", "userId":"100546"
}


### modificar una asignatura
PUT http://localhost:8080/subjects/bb713829-d7d3-4137-9ec7-fd105bc46f24
Content-Type: application/json

{
  "name":"Matematicas", "color":"#000000"
}

### eliminar una asignatura
DELETE http://localhost:8080/subjects/bb713829-d7d3-4137-9ec7-fd105bc46f24

### Test de tareas

### obteber tareas de una asignatura
GET http://localhost:8080/tasks/subject/777

### obtener tareas de un usuario
GET http://localhost:8080/tasks/user/100546

### Actualizar una tarea
PUT http://localhost:8080/tasks/988e61f8-8825-4869-8cf0-e25c722cfcf8
Content-Type: application/json

{
  "tittle": "Tarea de cálculo integral", "description": "Hacer las integrales", "subjectId": "777", "topicId": "00fa5630-e284-47f0-b7dd-af2fa6176e6f"
}

### crear una tarea
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "tittle": "Tarea de matematicas", "description": "Hacer la tarea de matematicas", "subjectId": "777", "topicId": "00fa5630-e284-47f0-b7dd-af2fa6176e6f"
}


### Obtener tipos de usuario
GET http://localhost:8080/topics/user/100546

### crear tipo
POST http://localhost:8080/topics
Content-Type: application/json

{
  "tittle": "Examen", "color": "#FFFFFF", "userId":"100546"
}

### actualizar tipo
PUT http://localhost:8080/topics/00fa5630-e284-47f0-b7dd-af2fa6176e6f
Content-Type: application/json

{
  "tittle": "Quiz", "color": "#00000", "userId":"100546"
}