
### Test de usuarios

### get de usuarios 
GET http://localhost:8080/users

### post de usuarios
POST http://localhost:8080/users
Content-Type: application/json

{
  "name":"Cristian Vargas", "email":"cristiandavidvargas717@gmail.com", "username":"crisdavalo", "password":"1234567890", "image":"https://firebasestorage.googleapis.com/v0/b/star-neutron.appspot.com/o/background-1.png?alt=media&token=53458d0f-f4bd-452a-be2a-dad4a74e3ad7"
}

### post de usuarios
POST http://localhost:8080/users
Content-Type: application/json

{
  "name":"Allicris", "email":"vargasloaizacristian@gmail.com", "username":"Allicris123", "password":"1234567890", "image":"https://firebasestorage.googleapis.com/v0/b/star-neutron.appspot.com/o/background-1.png?alt=media&token=53458d0f-f4bd-452a-be2a-dad4a74e3ad7"
}

### put de usuarios 
PUT http://localhost:8080/users
Content-Type: application/json

{
  "name":"Ryan", "username":"ryena456"
}

### verificar cuenta usuario
PUT http://localhost:8080/users/account/verify/f574f967-311c-4eb7-aee7-eb926a5f013d

### delete de usuarios
DELETE  http://localhost:8080/users











### Test de asignaturas

### obtener una asignatura por su id
GET http://localhost:8080/subjects/777


###obtener las asignaturas de un usuario
## no es necesario enviar el id del usuario, ya que se toma el id del usuario desde la cookie
GET http://localhost:8080/subjects/user/active

### crear una asignatura
POST http://localhost:8080/subjects
Content-Type: application/json

{
  "name":"HCI", "color":"#FFFFFF"
}


### modificar una asignatura
PUT http://localhost:8080/subjects/0fab415f-9265-4063-880a-c85690e8c6e9
Content-Type: application/json

{
  "name":"Admin de TI", "color":"#000000"
}

### eliminar una asignatura
DELETE http://localhost:8080/subjects/68701f50-52af-4d4c-a058-a507124f8287








### Test de tareas

### obteber tareas de una asignatura
GET http://localhost:8080/tasks/subject/15e560f2-3b36-4edd-ad6a-7b7dc22e50d2

### obtener tareas de un usuario
## no es necesario enviar el id del usuario, ya que se toma el id del usuario desde la cookie
GET http://localhost:8080/tasks/user/active

### Marcar una tarea como completada
PUT http://localhost:8080/tasks/mark/done/6f858f0f-2674-49de-bcd9-8a02e28ab9bd

### Marcar una tarea como activa otra vez (rollback)
PUT http://localhost:8080/tasks/roll/back/6f858f0f-2674-49de-bcd9-8a02e28ab9bd

### obtener las tareas completadas
GET http://localhost:8080/tasks/done/user


### Actualizar una tarea
PUT http://localhost:8080/tasks/33dd0b3d-eb3e-48f2-827c-ccae8ff2b60c
Content-Type: application/json

{
  "tittle": "Estudiar parcial", "description": "Estudiar para el parcial de algebra"
}

### crear una tarea
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "tittle": "Estudiar gauss jordan", "description": "Hacer algunos ejercicios", "subjectId": "15e560f2-3b36-4edd-ad6a-7b7dc22e50d2", "topicId": "0127aada-f597-440f-9a02-0b9a7640db62"
}

### eliminar una tarea
DELETE http://localhost:8080/tasks/70d293ce-1be1-4031-8e21-ce7659b0725b







### Test de topics


### Obtener tipos de usuario
GET http://localhost:8080/topics/user/active

### crear tipo
POST http://localhost:8080/topics
Content-Type: application/json

{
  "tittle": "Parcial", "color": "#FFFFFF", "userId":"f574f967-311c-4eb7-aee7-eb926a5f013d"
}

### actualizar tipo
PUT http://localhost:8080/topics/66f4a0eb-377d-4ce4-a02e-98082c550913
Content-Type: application/json

{
  "tittle": "Taller", "color": "#00000"
}

### eliminar un tipo
DELETE http://localhost:8080/topics/01b34836-3a80-49b9-94f9-6d7b6d27dbaa







### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "vargasloaizacristian@gmail.com", "password": "0987654321"
}

### logout
POST http://localhost:8080/logout
